### ISSUE TITLE
Possible bugs after integrating free repository as vendor library in pro

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#1318]
These 2 issues doesn't seem to be consistent, and can't confirm if are inherited or new bugs.
- Block styles: styles in editor doesn’t work when PublishPress Blocks is disabled through Dashboard
- Extended supported blocks it seems this feature is working despite being disabled after install; need more tests to confirm

Worth to test in fresh installs and in existing sites, to compare when settings are manually saved or using defaults.

On hold until after [all the new changes from this branch](https://github.com/publishpress/PublishPress-Blocks/tree/dev-workspace-2) are merged.

**Comment by andergmartins** [comment]
The second issue, Extended Supported Blocks is probably an issue with the logic on the conditional inside the settingsIsEnabled method: https://github.com/publishpress/PublishPress-Blocks/blob/dadcde6fb5ee9bce8ca5709ec39b2b0488358ec1/src/incl/advanced-gutenberg-main.php#L4136-L4143.

It will return true if the setting is not saved yet. It was probably coded that way so the features work by default before the user saves the settings for the first time with the actual setting. But even if the setting value is `0`, or `false` it will still return `true` because when the setting exists (no matter its value) it satisfies the first check in the `OR` condition, returning `true`.
