### ISSUE TITLE
Responsive support for grid view

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#153]
~~Similar to Columns Manager block > Responsive~~
___
Based on a suggestion from support: https://wordpress.org/support/topic/recent-post-columns-not-responsive-2/

**Comment by contactashish13** [comment]
@htmgarcia the columns manager block -> responsive is quite extensive and may not make sense with some of the options e.g. choosing `2/3 - 1/3` when 4 columns are selected may not work well. Do you want to recreate all the options from that block? Or would you want to make it simpler by having additional column fields for tablet and mobile like below?

![image](https://user-images.githubusercontent.com/12953439/111662121-a9e60380-8835-11eb-9f35-176d51f12c20.png)

**Comment by htmgarcia** [comment]
@contactashish13 you are correct. Please wait until I finish #360

**Comment by htmgarcia** [comment]
@contactashish13 I merged my changes into develop so you can do your magic.

**Comment by htmgarcia** [comment]
Please check the responsive support for the new Frontpage view as reference. We can use the same approach.  
<img width="1231" alt="Screen Shot 2021-03-19 at 17 47 06" src="https://user-images.githubusercontent.com/4999794/111852117-69d95c00-88db-11eb-95e7-cafe6835275f.png">

**Comment by contactashish13** [comment]
@htmgarcia Your changes work really well to make the block responsive so I believe nothing much needs to be done here. I only need to add more variations to the desktop layouts to allow for stacked (1 column), 2 column, 3 column and 4 column arrangements. Then all the user needs to do is use the Front Page layout instead of the grid layout and select the variation they want for their device. Please correct me if my assumption is wrong.

**Comment by htmgarcia** [comment]
@contactashish13 your point make sense. I can take care of this. Thanks!
