### ISSUE TITLE
Setting to not display the current post

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#161]
> Display the other posts from the same category except the current post.
_____
Requested from the WP forum: https://wordpress.org/support/topic/recent-posts-block-exclude-current-post/

Maybe there is an "Exclude" area? "Exclude current post" is one option. There is also a dropdown box to choose other posts to exclude.

**Comment by contactashish13** [comment]
@htmgarcia this can be done in multiple ways:

1. as you suggested, by populating a drop down to select the posts to skip. But this may become clunky because it will be a multiple select list with post titles as suggestions and titles can be rather long
2. adding an offset field that allows users to skip the first N posts from the display
3. adding a text field that accepts a comma separated list of words. Posts that have any of those words in their titles will be excluded
4. Like 3 above but with an additional control for content as well.

Thoughts?

**Comment by htmgarcia** [comment]
@contactashish13 when the Recent Posts block is inserted through a post (not a page), it would be useful a setting (enable/disable state) to not display the current post if is listed inside the block. 

Pease let me know if my explanation makes sense.
