### ISSUE TITLE
Custom Post Type support

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#194]
Requested by a user: https://wordpress.org/support/topic/custom-post-types-386/

![Latest-news-from-custom-post-type](https://user-images.githubusercontent.com/3868028/111367146-d00b7800-866a-11eb-955d-783aba6aa6e6.png)

**Comment by contactashish13** [comment]
@htmgarcia a CPT may have multiple taxonomies (as per the screenshot in https://github.com/publishpress/PublishPress-Blocks/issues/194#issue-759740762). I believe we need to add fields for all taxonomies supported so that a user can choose terms from each (not just one) of those taxonomies e.g. a movie could have a genre, a language and a country and all those fields should be filterable. Is that assumption correct?

**Comment by htmgarcia** [comment]
@contactashish13 I see your point. 

@stevejburge before CPT, maybe we could start with "page" support? A dropdown displaying "post" (default) and "page"?

**Comment by stevejburge** [comment]
Good question, @contactashish13 

Ok, let's start slowly with Pages

**Comment by htmgarcia** [comment]
@contactashish13 opened a separate issue - #372

**Comment by htmgarcia** [comment]
@contactashish13 please give a try to this one

**Comment by contactashish13** [comment]
@htmgarcia I am working on this. Just wanted to let you know that I should be able to complete it by tomorrow

**Comment by htmgarcia** [comment]
@contactashish13 please check #489 and #490
