### ISSUE TITLE
Category and Tags settings

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#401]
Can we put the Category and Tags setting next to each other? 

New labels
"Show content with these Categories"
"Show content with these Tags"

<img width="270" alt="Screen Shot 2021-03-30 at 10 06 20 AM" src="https://user-images.githubusercontent.com/3868028/113002941-45357d80-9140-11eb-9bee-ca3df33f449c.png">

**Comment by htmgarcia** [comment]
@stevejburge unfortunately is not possible due Order by, Categories and Number of Items fields are bundled in [QueryControls component](https://github.com/publishpress/PublishPress-Blocks/blob/develop/src/assets/blocks/recent-posts/block.jsx#L365-L377). 

We can only set "Show content with these Tags" label but since we can't do the same for "[Categories](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/query-controls/index.js#L85)", it won't be consistent.

**Comment by stevejburge** [comment]
Thanks - forget about that now. The label change has removed any need for it
