### ISSUE TITLE
Allow users to schedule block visibility

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#441]
<img width="281" alt="Screen Shot 2021-04-12 at 11 20 19 AM" src="https://user-images.githubusercontent.com/3868028/114419083-1fb56480-9b81-11eb-9ef1-c5eddd18dd98.png">

**Comment by htmgarcia** [comment]
@stevejburge this sounds like a Pro feature.

**Comment by stevejburge** [comment]
We could add a "Recurring" option:
<img width="569" alt="Screen Shot 2021-07-26 at 2 35 59 PM" src="https://user-images.githubusercontent.com/3868028/127040837-93957d82-7d82-4da2-a03c-2eab279e7c57.png">

**Comment by htmgarcia** [comment]
@contactashish13 we want to add a new panel available for any block (not only core and PublisPress Blocks) to decide optional publishing and unpublishing dates. We can implement a similar approach to Custom Styles, and in frontend we would display the block by checking the publish/unpublish dates as attributes.
<img width="281" alt="Screen Shot 2021-04-12 at 11 20 19 AM" src="https://user-images.githubusercontent.com/3868028/114419083-1fb56480-9b81-11eb-9ef1-c5eddd18dd98.png">
May you work on a proposal, please. This along with #520 are high priority.

**Comment by contactashish13** [comment]
@htmgarcia will this have a main settings page too - https://github.com/publishpress/PublishPress-Blocks/issues/441#issuecomment-886935216 ?

**Comment by stevejburge** [comment]
@htmgarcia @contactashish13 Yes. I think so. Users should be able to enable or disable this feature

**Comment by htmgarcia** [comment]
@contactashish13 we'll add the setting here:
![Screen Shot 2021-07-28 at 15 30 02](https://user-images.githubusercontent.com/4999794/127391517-43aeecce-f4cf-4d6c-b1b0-1d98121f68bd.png)

**Comment by contactashish13** [comment]
@htmgarcia @stevejburge can you please share access to the repo for the class `AdvancedGutenbergMain` and the views for the settings?

**Comment by htmgarcia** [comment]
@contactashish13 the class `AdvancedGutenbergMain` and the views are in free repository:
https://github.com/publishpress/PublishPress-Blocks/blob/develop/src/incl/advanced-gutenberg-main.php
https://github.com/publishpress/PublishPress-Blocks/tree/develop/src/incl/view

Since this is a Pro feature, you'll need to check also the Pro repository https://github.com/publishpress/PublishPress-Blocks-Pro/

**Comment by htmgarcia** [comment]
@contactashish13 sorry for being a pain, I still notice randomly seconds on the date time attributes. As example: 2021-08-16T13:03:**13** instead of 2021-08-16T13:03:**00**

In other tasks, please validate the code in Free repository to work only when Pro is detected. It can be done through a [constant exclusive in Pro repository](https://github.com/publishpress/PublishPress-Blocks/blob/master/src/incl/advanced-gutenberg-main.php#L409) in combination with [a method stored in Pro](https://github.com/publishpress/PublishPress-Blocks/blob/master/src/incl/advanced-gutenberg-main.php#L411).

Sample area to validate the output is https://github.com/publishpress/PublishPress-Blocks/pull/684/files#diff-a70ccaa1c88979cc421bd63f1b199aca60156c51710b3e95a70a7289a7972670R300-R322

**Comment by htmgarcia** [comment]
@stevejburge current progress:
![Screen Shot 2022-07-12 at 13 52 33](https://user-images.githubusercontent.com/4999794/178572565-7e73183d-04fb-4b3a-8248-b409cdc3a02d.png)

**Comment by stevejburge** [comment]
Thanks @htmgarcia 

The sidebar looks awesome. The eye in the center of the screen may be hard to see. Is that just a visual icon?

**Comment by htmgarcia** [comment]
Yes, is just a visual indicator that the block is using the schedule feature

**Comment by htmgarcia** [comment]
Issue with php rendered blocks
