### ISSUE TITLE
Block Access for Reusable Blocks 

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Blocks#593]
I wonder if we can show all reusable blocks here? This would allow admins to block some roles from using some reusable blocks

![Screen Shot 2021-06-14 at 3 28 22 PM](https://user-images.githubusercontent.com/3868028/121948503-5183ac80-cd25-11eb-8ba7-5bede7669a12.png)

**Comment by htmgarcia** [comment]
@stevejburge reusable blocks seems detected as a block type. I see your point and I'll take a look.

**Comment by htmgarcia** [comment]
@stevejburge since reusable blocks are set of one or more existing blocks, this could be handled as a separate feature. Maybe for Pro and after or together with #674

**Comment by stevejburge** [comment]
@htmgarcia i think this makes sense as a separate feature

**Comment by htmgarcia** [comment]
https://github.com/publishpress/PublishPress-Blocks-Pro/commit/dcd0c5071cfe626980e2e52fd2b2beab0119cd79

**Comment by htmgarcia** [comment]
@stevejburge current progress. 
![Screen Shot 2021-09-02 at 15 14 48](https://user-images.githubusercontent.com/4999794/131909996-20ed9760-c9fb-4896-9150-82b99adc18a2.png)
The remaining work involves doing research to figure out how to tell to Gutenberg editor to deactivate the blocks according to the Reusable Blocks screen.

**Comment by stevejburge** [comment]
Awesome, thanks @htmgarcia

**Comment by htmgarcia** [comment]
@contactashish13 are you familiar with `__experimentalReusableBlocks`? The plan is to update the list of reusable blocks in the Gutenberg editor to [not include some of them](https://user-images.githubusercontent.com/4999794/131909996-20ed9760-c9fb-4896-9150-82b99adc18a2.png).

Sample code for more context:
```
wp.data.dispatch('core/block-editor').updateSettings( { __experimentalReusableBlocks: [] } );
```
*The code above removes all the reusable blocks.

**Comment by contactashish13** [comment]
@htmgarcia I'm unable to see the Reusable Blocks tab. I have both Free and Pro activated and both are using the 2.12.0 branch. I copied [all changes from the repo](https://github.com/publishpress/PublishPress-Blocks-Pro/commit/dcd0c5071cfe626980e2e52fd2b2beab0119cd79) to the Pro plugin and also synced the Free plugin with the Free repo and even though I can see the code updated in the plugins, I do not see the tab. 

![image](https://user-images.githubusercontent.com/12953439/132287628-5c51e526-98de-4d8f-b0b7-17009c0daf9f.png)

PS - this functionality of manually copying stuff from the repo to the plugin introduces a lot of scope of errors. Isn't there a more efficient way?

**Comment by htmgarcia** [comment]
@contactashish13 in Github desktop be sure to chose the branches 2.12.0, then in terminal go to the `PublishPress-Blocks-Pro` folder and run in terminal `gulp bundle` to create the installer. 

*This feature is only available in Pro.

> PS - this functionality of manually copying stuff from the repo to the plugin introduces a lot of scope of errors. Isn't there a more efficient way?

Please feel free to suggest an improvement in this matter.

**Comment by contactashish13** [comment]
@htmgarcia have pushed in my changes (https://github.com/publishpress/PublishPress-Blocks-Pro/pull/40). 

I have followed the below steps:

1. Create a reusable block (reusable-block-1)
2. Go to a post and see list of reusable locks - reusable-block-1 shows
3. Toggle reusable-block-1 as inactive in settings
4. Go to a post and the reusable locks tab disappears
5. Create a reusable block (reusable-block-2), which is by default active for the user
6. Go to a post and see list of reusable locks - reusable-block-2 shows
7. Toggle reusable-block-1 as active in settings
8. Go to a post and see list of reusable locks - reusable-block-1 and reusable-block-2 show
9. Toggle reusable-block-1 and reusable-block-2 as inactive in settings
10. Go to a post and the reusable locks tab disappears

> Please feel free to suggest an improvement in this matter.

If we are already watching files, can we not fire an automatic copy rather than a manual copy?

**Comment by htmgarcia** [comment]
@contactashish13 thanks! The code make sense, however the blocks are not being deactivated in the test process when having more than one reusable block. 
![Screen Shot 2021-09-13 at 11 27 56](https://user-images.githubusercontent.com/4999794/133121763-e4a46981-0623-4560-add5-50e5d342d606.png)
![Screen Shot 2021-09-13 at 11 28 11](https://user-images.githubusercontent.com/4999794/133121769-c5cfce0f-aa05-490f-b146-07b463000e34.png)
It could be that the reusable blocks list is being refreshed on background (e.g. I noticed a blink in Reusable blocks tab) and that causes [the dispatch to be overridden](https://github.com/publishpress/PublishPress-Blocks-Pro/pull/40/files#diff-a665cc474eac9197d45c03eb6d9efc34765c5e8e5d30270fd74bb846871fda08R119) due only runs once due the `subscribe_called` boolean?

**Comment by contactashish13** [comment]
@htmgarcia I added 1 more reusable block and made only one active for the user role. I see only that visible in the reusable blocks section. I do see the `updateSettings` settings being called twice though so the use case seems to work for me. It could be because my WP instance is slow.

![image](https://user-images.githubusercontent.com/12953439/133212934-1adf7006-a7e7-40d5-8df5-b7172077d048.png)

![image](https://user-images.githubusercontent.com/12953439/133212892-03e44755-6231-4037-aab8-4d96f59c68d5.png)

That said, I have added code to update the settings outside of the subscribe method. Can you check if that works?

**Comment by htmgarcia** [comment]
@contactashish13 that last commit did the trick. Awesome job!
