### ISSUE TITLE
Lets make a normal class to set color of the one button only

### ISSUE THREAD

**Issue by w0wan** [publishpress/PublishPress-Blocks#697]
Hello!

https://ibb.co/72WzL5r 
https://ibb.co/0JMnkTq 

my entire site https://themes-wordpress.ru/ is made in blue tones.
on one of the pages https://themes-wordpress.ru/sayt_tovarov/ I decided to repaint the "Advanced Button"  in one block.
the "Advanced Button" was blue (red on hover) and turned brown (yellow on hover).
and I have repainted all the buttons in all blocks on the page, and not just in this block!
but on the index https://themes-wordpress.ru/ there is no block with a brown button and all the buttons remain as they were - blue.

Lets make a normal individual class to set the color of the button only for 1 block and not for all!

**Comment by w0wan** [comment]
Today I put the last block on the block with the bottom button and all the buttons turned blue.

**Comment by w0wan** [comment]
* Today I put the last block the block with the blue button and all buttons in all blocks turned blue.

**Comment by htmgarcia** [comment]
Hi @w0wan,
the issue is all the buttons were duplicated, and the id was the same when duplicating, so the color of 1 block was applied to all the rest. We actually fixed this time ago.

Please edit the pages and save. A new id should be assigned automatically to each instance of the Advanced Button block.
