### ISSUE TITLE
Sometimes changes are not saved

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Blocks#710]
This happens randomly. Followed this case scenario: https://wordpress.org/support/topic/cannot-save-changes-to-an-existing-advanced-table/#post-14846921

**Comment by htmgarcia** [comment]
@contactashish13 the issue is easy to reproduce, but the result is inconsistent. 
[This screencast explains how](https://wordpress.org/support/topic/cannot-save-changes-to-an-existing-advanced-table/#post-14846921).

I appreciate your expertise on this one.

**Comment by contactashish13** [comment]
@htmgarcia in my testing it 
- always happens when the editor is loaded and the first edits are made
- sometimes happens after the block has been allowed to load and the first edits above

Also it looks like the HTML that is sent to save post and auto save is not updated sometimes, like there is some delay between the keystroke completion and the firing of the request. Is this what you see at your end too? I will continue to investigate and let you know what I find.

**Comment by htmgarcia** [comment]
@contactashish13 this seems to be the first place to look:

> the HTML that is sent to save post and auto save is not updated sometimes

Try adding `console.log()` in places that handle the content of the table cells to notice the content of some cells is missing. As example, add the output before https://github.com/publishpress/PublishPress-Blocks/blob/develop/src/assets/blocks/advtable/block.jsx#L147 while testing the case scenario:
`console.log(cell)`;

**Comment by contactashish13** [comment]
@htmgarcia Here is how I reproduced this behavior:

1. create a default advanced table block with empty rows
2. save post
3. refresh post
4. as soon as the block loads, add content to a cell - **this is not registered in the `updateCellContent` callback** [here](https://github.com/publishpress/PublishPress-Blocks/blob/develop/src/assets/blocks/advtable/block.jsx#L701) 
5. update another cell - **this is registered**
6. save post (only the second cell update is saved)
7. as soon as the block loads, add content to another cell - **this is not registered in the `updateCellContent` callback**
8. update another cell - **this is registered**
9. save post (only the second cell update is saved)
10. as soon as the block loads, focus on a cell that already has content and then add content to another cell - **this is registered**
11. refresh the post
12. as soon as the block loads, focus on a cell that already has content and add content to same cell - **this is registered**

So it looks like the first content update in an empty cell is not registered because of [this if block](https://github.com/publishpress/PublishPress-Blocks/blob/develop/src/assets/blocks/advtable/block.jsx#L703-L705). I'll continue to explore but just wanted to give you an interim update.

I'm curious about why you are using a [timeout](https://github.com/publishpress/PublishPress-Blocks/blob/develop/src/assets/blocks/advtable/block.jsx#L871). Even if I reduce the timeout value to 500, it doesn't work.

**Comment by htmgarcia** [comment]
@contactashish13 definitely this is not an easy bug, however I appreciate your expertise to have this fixed.

**Comment by contactashish13** [comment]
@htmgarcia can you please test with https://github.com/publishpress/PublishPress-Blocks/pull/749? It seems to solve this issue but I don't know if it introduces some other bug.

**Comment by htmgarcia** [comment]
I attach beta package with the fix for testing purposes:
[advanced-gutenberg-2.11.3b3.zip](https://github.com/publishpress/PublishPress-Blocks/files/7865449/advanced-gutenberg-2.11.3b3.zip)
